{
 "title": "APT: CISAIranianAPT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Account_Manipulation_attack_action_792aaa39",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Account_Manipulation_attack_action_792aaa39"
    }
   ]
  },
  {
   "title": "CISAIranianAPTOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_CISAIranianAPTOccurred" }
   ]
  },
  {
   "title": "Default_Accounts_attack_action_57e36a89",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Default_Accounts_attack_action_57e36a89"
    }
   ]
  },
  {
   "title": "Disable_or_Modify_Tools_attack_action_1d283005",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Disable_or_Modify_Tools_attack_action_1d283005"
    }
   ]
  },
  {
   "title": "Disable_or_Modify_Tools_attack_action_56ca6034",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Disable_or_Modify_Tools_attack_action_56ca6034"
    }
   ]
  },
  {
   "title": "Domain_Account_attack_action_d8ba9c2f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Domain_Account_attack_action_d8ba9c2f"
    }
   ]
  },
  {
   "title": "Exploit_Public_Facing_Applicat_attack_action_b6143619",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploit_Public_Facing_Applicat_attack_action_b6143619"
    }
   ]
  },
  {
   "title": "File_Deletion_attack_action_9c30cd6b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_File_Deletion_attack_action_9c30cd6b"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_0606c44c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_0606c44c"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_3fbadab6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_3fbadab6"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_cfae690b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_cfae690b"
    }
   ]
  },
  {
   "title": "Internet_Connection_Discovery_attack_action_69978025",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Internet_Connection_Discovery_attack_action_69978025"
    }
   ]
  },
  {
   "title": "LSASS_Memory_attack_action_99406b0d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_LSASS_Memory_attack_action_99406b0d"
    }
   ]
  },
  {
   "title": "Lateral_Movement_attack_action_c55d72d0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Lateral_Movement_attack_action_c55d72d0"
    }
   ]
  },
  {
   "title": "Lateral_Tool_Transfer_attack_action_ee829570",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Lateral_Tool_Transfer_attack_action_ee829570"
    }
   ]
  },
  {
   "title": "Local_Account_attack_action_857eaaa1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Local_Account_attack_action_857eaaa1"
    }
   ]
  },
  {
   "title": "PowerShell_attack_action_0d573bcd",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_PowerShell_attack_action_0d573bcd"
    }
   ]
  },
  {
   "title": "PowerShell_attack_action_2f9114f6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_PowerShell_attack_action_2f9114f6"
    }
   ]
  },
  {
   "title": "Proxy_attack_action_4beb5555",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Proxy_attack_action_4beb5555"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_52069465",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_52069465"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_7e2175b8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_7e2175b8"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_f8daeaa9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_f8daeaa9"
    }
   ]
  },
  {
   "title": "Remote_System_Discovery_attack_action_45e8b0a1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_System_Discovery_attack_action_45e8b0a1"
    }
   ]
  },
  {
   "title": "Scheduled_Task_attack_action_de68b787",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Scheduled_Task_attack_action_de68b787"
    }
   ]
  }
 ]
}