{
 "title": "APT: WhisperGate",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ingress_Tool_Transfer_attack_action_c89289c0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_c89289c0"
    }
   ]
  },
  {
   "title": "Valid_Accounts_attack_action_b28935d3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Valid_Accounts_attack_action_b28935d3"
    }
   ]
  },
  {
   "title": "WhisperGateOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_WhisperGateOccurred" }
   ]
  },
  {
   "title": "attack_condition_d4067e78_456d_attack_condition_d4067e78",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_d4067e78_456d_attack_condition_d4067e78"
    }
   ]
  }
 ]
}