{
 "title": "APT: FIN13Case2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active_Scanning_attack_action_47fdc13f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Active_Scanning_attack_action_47fdc13f"
    }
   ]
  },
  {
   "title": "Exploit_Public_Facing_Applicat_attack_action_81e5c5eb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploit_Public_Facing_Applicat_attack_action_81e5c5eb"
    }
   ]
  },
  {
   "title": "Exploitation_for_Client_Execut_attack_action_6c480520",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploitation_for_Client_Execut_attack_action_6c480520"
    }
   ]
  },
  {
   "title": "FIN13Case2Occurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_FIN13Case2Occurred" }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_6a89f34f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_6a89f34f"
    }
   ]
  },
  {
   "title": "LSASS_Memory_attack_action_482cf545",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_LSASS_Memory_attack_action_482cf545"
    }
   ]
  },
  {
   "title": "Web_Shell_attack_action_fcd49b6d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Web_Shell_attack_action_fcd49b6d"
    }
   ]
  },
  {
   "title": "attack_condition_2842d171_01e5_attack_condition_2842d171",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_2842d171_01e5_attack_condition_2842d171"
    }
   ]
  }
 ]
}