{
 "title": "APT: MuddyWater",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "MuddyWaterOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_MuddyWaterOccurred" }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_2cdde459",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_2cdde459"
    }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_eba614a5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_eba614a5"
    }
   ]
  },
  {
   "title": "attack_condition_31948bdf_3667_attack_condition_31948bdf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_31948bdf_3667_attack_condition_31948bdf"
    }
   ]
  },
  {
   "title": "attack_condition_5b19b30a_2f60_attack_condition_5b19b30a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_5b19b30a_2f60_attack_condition_5b19b30a"
    }
   ]
  }
 ]
}