{
 "title": "APT: SWIFTHeist",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Accounts_opened_illegally_attack_action_a0340333",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Accounts_opened_illegally_attack_action_a0340333"
    }
   ]
  },
  {
   "title": "Exploit_Public_Facing_Applicat_attack_action_d6d5a619",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploit_Public_Facing_Applicat_attack_action_d6d5a619"
    }
   ]
  },
  {
   "title": "SWIFTHeistOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_SWIFTHeistOccurred" }
   ]
  },
  {
   "title": "Send_money_to_Philippines_acco_attack_action_3f76a094",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Send_money_to_Philippines_acco_attack_action_3f76a094"
    }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_d958677e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_d958677e"
    }
   ]
  },
  {
   "title": "attack_operator_90340c1f_69b1__attack_operator_90340c1f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_90340c1f_69b1__attack_operator_90340c1f"
    }
   ]
  },
  {
   "title": "attack_operator_e66b7512_df8f__attack_operator_e66b7512",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_e66b7512_df8f__attack_operator_e66b7512"
    }
   ]
  }
 ]
}