{
 "title": "APT: TargetBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client_Configurations_attack_action_9ac3cd71",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Client_Configurations_attack_action_9ac3cd71"
    }
   ]
  },
  {
   "title": "Search_Engines_attack_action_d2a45c19",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Search_Engines_attack_action_d2a45c19"
    }
   ]
  },
  {
   "title": "TargetBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_TargetBreachOccurred" }
   ]
  },
  {
   "title": "attack_operator_11263b9e_012f__attack_operator_11263b9e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_11263b9e_012f__attack_operator_11263b9e"
    }
   ]
  }
 ]
}