{
 "title": "APT: Gootloader",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Compromise_Infrastructure_attack_action_35f13ec8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Infrastructure_attack_action_35f13ec8"
    }
   ]
  },
  {
   "title": "GootloaderOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_GootloaderOccurred" }
   ]
  },
  {
   "title": "attack_condition_01e917ac_a5d7_attack_condition_01e917ac",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_01e917ac_a5d7_attack_condition_01e917ac"
    }
   ]
  }
 ]
}