{
 "title": "APT: NotPetya",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Compromise_Software_Supply_Cha_attack_action_460b67ee",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Software_Supply_Cha_attack_action_460b67ee"
    }
   ]
  },
  {
   "title": "Compromise_Software_Supply_Cha_attack_action_9ac3cd71",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Software_Supply_Cha_attack_action_9ac3cd71"
    }
   ]
  },
  {
   "title": "Malware_Privilege_Discovery_attack_action_3d221636",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malware_Privilege_Discovery_attack_action_3d221636"
    }
   ]
  },
  {
   "title": "Masquerading_attack_action_698fd2b3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Masquerading_attack_action_698fd2b3"
    }
   ]
  },
  {
   "title": "NotPetyaOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_NotPetyaOccurred" }
   ]
  },
  {
   "title": "Search_Open_WebsitesDomains_attack_action_605180eb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Search_Open_WebsitesDomains_attack_action_605180eb"
    }
   ]
  },
  {
   "title": "Security_Software_Discovery_attack_action_371fe05f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Security_Software_Discovery_attack_action_371fe05f"
    }
   ]
  },
  {
   "title": "Supply_Chain_Compromise_attack_action_0cfbada8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Supply_Chain_Compromise_attack_action_0cfbada8"
    }
   ]
  },
  {
   "title": "attack_condition_3b06b8c3_c293_attack_condition_3b06b8c3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_3b06b8c3_c293_attack_condition_3b06b8c3"
    }
   ]
  },
  {
   "title": "attack_condition_6c666fe2_0a6c_attack_condition_6c666fe2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_6c666fe2_0a6c_attack_condition_6c666fe2"
    }
   ]
  },
  {
   "title": "attack_condition_7f9d0200_8303_attack_condition_7f9d0200",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_7f9d0200_8303_attack_condition_7f9d0200"
    }
   ]
  },
  {
   "title": "attack_condition_d3033b02_3cdc_attack_condition_d3033b02",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_d3033b02_3cdc_attack_condition_d3033b02"
    }
   ]
  }
 ]
}