{
 "title": "APT: UberBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Compromise_Accounts_attack_action_b1b20bb1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Accounts_attack_action_b1b20bb1"
    }
   ]
  },
  {
   "title": "UberBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_UberBreachOccurred" }
   ]
  },
  {
   "title": "attack_condition_75170181_d3e4_attack_condition_75170181",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_75170181_d3e4_attack_condition_75170181"
    }
   ]
  }
 ]
}