{
 "title": "APT: FIN13Case1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active_Scanning_attack_action_05411f8d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Active_Scanning_attack_action_05411f8d"
    }
   ]
  },
  {
   "title": "FIN13Case1Occurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_FIN13Case1Occurred" }
   ]
  },
  {
   "title": "Vulnerability_Scanning_attack_action_06617ed8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Vulnerability_Scanning_attack_action_06617ed8"
    }
   ]
  },
  {
   "title": "attack_condition_18044ef4_83a8_attack_condition_18044ef4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_18044ef4_83a8_attack_condition_18044ef4"
    }
   ]
  }
 ]
}