{
 "title": "APT: DFIR_BumbleBeeRound2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Command_and_Scripting_Interpre_attack_action_52551dbb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Scripting_Interpre_attack_action_52551dbb"
    }
   ]
  },
  {
   "title": "DFIR_BumbleBeeRound2Occurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_DFIR_BumbleBeeRound2Occurred"
    }
   ]
  },
  {
   "title": "Domain_Account_attack_action_4f144a9a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Domain_Account_attack_action_4f144a9a"
    }
   ]
  },
  {
   "title": "Domain_Trust_Discovery_attack_action_f636129f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Domain_Trust_Discovery_attack_action_f636129f"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_1d4f33a8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_1d4f33a8"
    }
   ]
  },
  {
   "title": "Network_Share_Discovery_attack_action_1da9c661",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Network_Share_Discovery_attack_action_1da9c661"
    }
   ]
  },
  {
   "title": "Process_Injection_attack_action_055084d8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Process_Injection_attack_action_055084d8"
    }
   ]
  },
  {
   "title": "Rundll32_attack_action_3d2e236c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Rundll32_attack_action_3d2e236c"
    }
   ]
  },
  {
   "title": "Shortcut_Modification_attack_action_5bde19de",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Shortcut_Modification_attack_action_5bde19de"
    }
   ]
  },
  {
   "title": "Windows_Management_Instrumenta_attack_action_a4a665d0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Windows_Management_Instrumenta_attack_action_a4a665d0"
    }
   ]
  },
  {
   "title": "attack_operator_f33a8aa0_fe02__attack_operator_f33a8aa0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_f33a8aa0_fe02__attack_operator_f33a8aa0"
    }
   ]
  }
 ]
}