{
 "title": "APT: Shamoon",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Embedded_Payloads_attack_action_5042c11d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Embedded_Payloads_attack_action_5042c11d"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_45238a64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_45238a64"
    }
   ]
  },
  {
   "title": "ShamoonOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_ShamoonOccurred" }
   ]
  },
  {
   "title": "attack_condition_b39f76f6_09ed_attack_condition_b39f76f6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_b39f76f6_09ed_attack_condition_b39f76f6"
    }
   ]
  }
 ]
}