{
 "title": "APT: CISAAA22_138BVMWareWorkspace_TA2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CISAAA22_138BVMWareWorkspace_TA2Occurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_CISAAA22_138BVMWareWorkspace_TA2Occurred"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_4b5c1c23",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_4b5c1c23"
    }
   ]
  },
  {
   "title": "Web_Protocols_attack_action_1249135e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Web_Protocols_attack_action_1249135e"
    }
   ]
  },
  {
   "title": "attack_condition_98f53f54_8560_attack_condition_98f53f54",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_98f53f54_8560_attack_condition_98f53f54"
    }
   ]
  }
 ]
}