{
 "title": "APT: ContiPWC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ContiPWCOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_ContiPWCOccurred" }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_2a8b2d9c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_2a8b2d9c"
    }
   ]
  },
  {
   "title": "attack_condition_f8f14cd5_8cb3_attack_condition_f8f14cd5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_f8f14cd5_8cb3_attack_condition_f8f14cd5"
    }
   ]
  }
 ]
}