{
 "title": "APT: CISAAA22_138BVMWareWorkspace_TA1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CISAAA22_138BVMWareWorkspace_TA1Occurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_CISAAA22_138BVMWareWorkspace_TA1Occurred"
    }
   ]
  },
  {
   "title": "Exploitation_for_Client_Execut_attack_action_780d1e10",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploitation_for_Client_Execut_attack_action_780d1e10"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_427f3a5b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_427f3a5b"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_7d09b87c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_7d09b87c"
    }
   ]
  },
  {
   "title": "Web_Protocols_attack_action_87cf2efa",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Web_Protocols_attack_action_87cf2efa"
    }
   ]
  },
  {
   "title": "attack_operator_1e41f6c5_95dc__attack_operator_1e41f6c5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_1e41f6c5_95dc__attack_operator_1e41f6c5"
    }
   ]
  }
 ]
}