{
 "title": "APT: ExampleAttackTree",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Acquire_User_Credentials_From__attack_action_d3a9b4b8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Acquire_User_Credentials_From__attack_action_d3a9b4b8"
    }
   ]
  },
  {
   "title": "Associate_Data_with_Unique_Dev_attack_action_2af74e9a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Associate_Data_with_Unique_Dev_attack_action_2af74e9a"
    }
   ]
  },
  {
   "title": "Associate_Tracker_With_a_Contr_attack_action_8f7c3f72",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Associate_Tracker_With_a_Contr_attack_action_8f7c3f72"
    }
   ]
  },
  {
   "title": "Browser_Session_Hijacking_attack_action_37b85046",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Browser_Session_Hijacking_attack_action_37b85046"
    }
   ]
  },
  {
   "title": "Compile_Known_User_Data_attack_action_2867ece0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compile_Known_User_Data_attack_action_2867ece0"
    }
   ]
  },
  {
   "title": "Configure_an_Alternative_Serve_attack_action_e5ddaf28",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Configure_an_Alternative_Serve_attack_action_e5ddaf28"
    }
   ]
  },
  {
   "title": "Determine_Approximate_Location_attack_action_89bfd82d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Determine_Approximate_Location_attack_action_89bfd82d"
    }
   ]
  },
  {
   "title": "Device_Data_Is_Unencrypted_attack_action_ec135ca7",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Device_Data_Is_Unencrypted_attack_action_ec135ca7"
    }
   ]
  },
  {
   "title": "Disable_Authentication_attack_action_87dca2ec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Disable_Authentication_attack_action_87dca2ec"
    }
   ]
  },
  {
   "title": "Disable_Encryption_attack_action_0f2a453c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Disable_Encryption_attack_action_0f2a453c"
    }
   ]
  },
  {
   "title": "Downloading_Manipulated_Browse_attack_action_643f38b0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Downloading_Manipulated_Browse_attack_action_643f38b0"
    }
   ]
  },
  {
   "title": "Eavesdrop_on_Device_Communicat_attack_action_6bdf557c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Eavesdrop_on_Device_Communicat_attack_action_6bdf557c"
    }
   ]
  },
  {
   "title": "ExampleAttackTreeOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_ExampleAttackTreeOccurred" }
   ]
  },
  {
   "title": "Find_a_Free_Copy_of_the_Datase_attack_action_2d7c7f99",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Find_a_Free_Copy_of_the_Datase_attack_action_2d7c7f99"
    }
   ]
  },
  {
   "title": "Get_Within_Wireless_Range_of_t_attack_action_8df074e4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Get_Within_Wireless_Range_of_t_attack_action_8df074e4"
    }
   ]
  },
  {
   "title": "Get_Within_Wireless_Range_of_t_attack_action_9cf8b16c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Get_Within_Wireless_Range_of_t_attack_action_9cf8b16c"
    }
   ]
  },
  {
   "title": "Learn_Tracker_Serial_Number_attack_action_84217add",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Learn_Tracker_Serial_Number_attack_action_84217add"
    }
   ]
  },
  {
   "title": "Local_Data_is_Encrypted_attack_action_0f3f233c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Local_Data_is_Encrypted_attack_action_0f3f233c"
    }
   ]
  },
  {
   "title": "Prompt_User_for_Login_Informat_attack_action_eda0131b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Prompt_User_for_Login_Informat_attack_action_eda0131b"
    }
   ]
  },
  {
   "title": "Purchase_Dataset_Containing_Us_attack_action_32234997",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Purchase_Dataset_Containing_Us_attack_action_32234997"
    }
   ]
  },
  {
   "title": "Purchase_User_Credentials_attack_action_4fab276c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Purchase_User_Credentials_attack_action_4fab276c"
    }
   ]
  },
  {
   "title": "Push_Malicious_Firmware_Update_attack_action_b94fa2a2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Push_Malicious_Firmware_Update_attack_action_b94fa2a2"
    }
   ]
  },
  {
   "title": "Re_Associate_Device_To_Control_attack_action_be373544",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Re_Associate_Device_To_Control_attack_action_be373544"
    }
   ]
  },
  {
   "title": "Record_User_Login_Information_attack_action_e5f3487d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Record_User_Login_Information_attack_action_e5f3487d"
    }
   ]
  },
  {
   "title": "Replace_Tracker_After_Firmware_attack_action_fe72b1b9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Replace_Tracker_After_Firmware_attack_action_fe72b1b9"
    }
   ]
  },
  {
   "title": "Replay_Authentication_Sequence_attack_action_6bd52eec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Replay_Authentication_Sequence_attack_action_6bd52eec"
    }
   ]
  },
  {
   "title": "Steal_Tracker_attack_action_5f9f61a9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Steal_Tracker_attack_action_5f9f61a9"
    }
   ]
  },
  {
   "title": "Synthesize_Known_User_Data_and_attack_action_ba3f0f10",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Synthesize_Known_User_Data_and_attack_action_ba3f0f10"
    }
   ]
  },
  {
   "title": "Trigger_Synchronization_Over_B_attack_action_8f2b5ae8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Trigger_Synchronization_Over_B_attack_action_8f2b5ae8"
    }
   ]
  },
  {
   "title": "User_Interacts_With_Malicious__attack_action_f6e15450",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_User_Interacts_With_Malicious__attack_action_f6e15450"
    }
   ]
  },
  {
   "title": "attack_operator_16805ea6_27ac__attack_operator_16805ea6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_16805ea6_27ac__attack_operator_16805ea6"
    }
   ]
  },
  {
   "title": "attack_operator_1c6c2cdd_ebbe__attack_operator_1c6c2cdd",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_1c6c2cdd_ebbe__attack_operator_1c6c2cdd"
    }
   ]
  },
  {
   "title": "attack_operator_212e23fe_c04f__attack_operator_212e23fe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_212e23fe_c04f__attack_operator_212e23fe"
    }
   ]
  },
  {
   "title": "attack_operator_341a85ab_69d4__attack_operator_341a85ab",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_341a85ab_69d4__attack_operator_341a85ab"
    }
   ]
  },
  {
   "title": "attack_operator_47cbb476_bb10__attack_operator_47cbb476",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_47cbb476_bb10__attack_operator_47cbb476"
    }
   ]
  },
  {
   "title": "attack_operator_55c18a7c_69a0__attack_operator_55c18a7c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_55c18a7c_69a0__attack_operator_55c18a7c"
    }
   ]
  },
  {
   "title": "attack_operator_567d1a9c_069b__attack_operator_567d1a9c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_567d1a9c_069b__attack_operator_567d1a9c"
    }
   ]
  },
  {
   "title": "attack_operator_70120336_4ff9__attack_operator_70120336",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_70120336_4ff9__attack_operator_70120336"
    }
   ]
  },
  {
   "title": "attack_operator_7cf24d0d_f1bf__attack_operator_7cf24d0d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_7cf24d0d_f1bf__attack_operator_7cf24d0d"
    }
   ]
  },
  {
   "title": "attack_operator_8cda965c_9868__attack_operator_8cda965c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_8cda965c_9868__attack_operator_8cda965c"
    }
   ]
  },
  {
   "title": "attack_operator_92eb629c_d257__attack_operator_92eb629c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_92eb629c_d257__attack_operator_92eb629c"
    }
   ]
  },
  {
   "title": "attack_operator_a8c00ec1_1a8d__attack_operator_a8c00ec1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_a8c00ec1_1a8d__attack_operator_a8c00ec1"
    }
   ]
  },
  {
   "title": "attack_operator_bab5422f_0bdb__attack_operator_bab5422f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_bab5422f_0bdb__attack_operator_bab5422f"
    }
   ]
  },
  {
   "title": "attack_operator_bb5ec01a_10e9__attack_operator_bb5ec01a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_bb5ec01a_10e9__attack_operator_bb5ec01a"
    }
   ]
  },
  {
   "title": "attack_operator_bd09a07e_82f1__attack_operator_bd09a07e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_bd09a07e_82f1__attack_operator_bd09a07e"
    }
   ]
  },
  {
   "title": "attack_operator_c20eb04a_ffa7__attack_operator_c20eb04a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_c20eb04a_ffa7__attack_operator_c20eb04a"
    }
   ]
  },
  {
   "title": "attack_operator_d908dbfe_4518__attack_operator_d908dbfe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_d908dbfe_4518__attack_operator_d908dbfe"
    }
   ]
  },
  {
   "title": "attack_operator_ddeb6e7b_5992__attack_operator_ddeb6e7b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_ddeb6e7b_5992__attack_operator_ddeb6e7b"
    }
   ]
  },
  {
   "title": "attack_operator_e51fb8f0_ee0f__attack_operator_e51fb8f0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_e51fb8f0_ee0f__attack_operator_e51fb8f0"
    }
   ]
  },
  {
   "title": "attack_operator_e8cff81f_61a2__attack_operator_e8cff81f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_e8cff81f_61a2__attack_operator_e8cff81f"
    }
   ]
  },
  {
   "title": "attack_operator_f4373071_24c9__attack_operator_f4373071",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_f4373071_24c9__attack_operator_f4373071"
    }
   ]
  }
 ]
}