{
 "title": "APT: CISAAA22_138BVMWareWorkspace_Alt",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Archive_via_Utility_attack_action_7fa1a34d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Archive_via_Utility_attack_action_7fa1a34d"
    }
   ]
  },
  {
   "title": "CISAAA22_138BVMWareWorkspace_AltOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_CISAAA22_138BVMWareWorkspace_AltOccurred"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_35c17809",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_35c17809"
    }
   ]
  },
  {
   "title": "Command_and_Scripting_Interpre_attack_action_3c019d2c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Scripting_Interpre_attack_action_3c019d2c"
    }
   ]
  },
  {
   "title": "Discovery_attack_action_1472fccf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Discovery_attack_action_1472fccf"
    }
   ]
  },
  {
   "title": "Exploitation_for_Client_Execut_attack_action_84454574",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploitation_for_Client_Execut_attack_action_84454574"
    }
   ]
  },
  {
   "title": "Exploitation_for_Privilege_Esc_attack_action_401fbfb9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploitation_for_Privilege_Esc_attack_action_401fbfb9"
    }
   ]
  },
  {
   "title": "File_and_Directory_Discovery_attack_action_747d2282",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_File_and_Directory_Discovery_attack_action_747d2282"
    }
   ]
  },
  {
   "title": "Indicator_Removal_attack_action_24692f77",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Indicator_Removal_attack_action_24692f77"
    }
   ]
  },
  {
   "title": "Indicator_Removal_attack_action_298530ff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Indicator_Removal_attack_action_298530ff"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_3c3fea04",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_3c3fea04"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_6dbde84b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_6dbde84b"
    }
   ]
  }
 ]
}