{
 "title": "APT: SearchAwesomeAdware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Adversary_in_the_Middle_attack_action_912ab340",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Adversary_in_the_Middle_attack_action_912ab340"
    }
   ]
  },
  {
   "title": "Browser_Session_Hijacking_attack_action_3ab0e565",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Browser_Session_Hijacking_attack_action_3ab0e565"
    }
   ]
  },
  {
   "title": "Command_and_Scripting_Interpre_attack_action_5fb732fb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Scripting_Interpre_attack_action_5fb732fb"
    }
   ]
  },
  {
   "title": "File_Deletion_attack_action_9701d9a7",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_File_Deletion_attack_action_9701d9a7"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_91742a64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_91742a64"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_ef2455bc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_ef2455bc"
    }
   ]
  },
  {
   "title": "Install_Root_Certificate_attack_action_638fbd7e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Install_Root_Certificate_attack_action_638fbd7e"
    }
   ]
  },
  {
   "title": "Malicious_File_attack_action_cb85f8b2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malicious_File_attack_action_cb85f8b2"
    }
   ]
  },
  {
   "title": "Malvertising_attack_action_d545cf7c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malvertising_attack_action_d545cf7c"
    }
   ]
  },
  {
   "title": "Proxy_attack_action_f829939a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Proxy_attack_action_f829939a"
    }
   ]
  },
  {
   "title": "SearchAwesomeAdwareOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_SearchAwesomeAdwareOccurred" }
   ]
  },
  {
   "title": "Subvert_Trust_Controls_attack_action_f6677d9d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Subvert_Trust_Controls_attack_action_f6677d9d"
    }
   ]
  }
 ]
}