{
 "title": "APT: MaastrichtUniversityRansomware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "MaastrichtUniversityRansomwareOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_MaastrichtUniversityRansomwareOccurred"
    }
   ]
  },
  {
   "title": "Phishing_Spearphishing_Attachm_attack_action_e846ce14",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Phishing_Spearphishing_Attachm_attack_action_e846ce14"
    }
   ]
  },
  {
   "title": "attack_condition_992c80ba_7ccb_attack_condition_992c80ba",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_992c80ba_7ccb_attack_condition_992c80ba"
    }
   ]
  }
 ]
}