{
 "title": "APT: RagnarLocker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Brute_Force_attack_action_3e22a477",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Brute_Force_attack_action_3e22a477"
    }
   ]
  },
  {
   "title": "RagnarLockerOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_RagnarLockerOccurred" }
   ]
  },
  {
   "title": "Valid_Accounts_attack_action_dac00d37",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Valid_Accounts_attack_action_dac00d37"
    }
   ]
  },
  {
   "title": "attack_operator_2cab6c72_de7c__attack_operator_2cab6c72",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_2cab6c72_de7c__attack_operator_2cab6c72"
    }
   ]
  }
 ]
}