{
 "title": "APT: IvantiVulnerabilities",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Archive_via_Utility_attack_action_9bd0a0d1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Archive_via_Utility_attack_action_9bd0a0d1"
    }
   ]
  },
  {
   "title": "Clear_Linux_or_Mac_System_Logs_attack_action_f3ecd4a2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Clear_Linux_or_Mac_System_Logs_attack_action_f3ecd4a2"
    }
   ]
  },
  {
   "title": "Client_Configurations_attack_action_7dd03660",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Client_Configurations_attack_action_7dd03660"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_ba3cc611",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_ba3cc611"
    }
   ]
  },
  {
   "title": "Compromise_Host_Software_Binar_attack_action_06fe9325",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Host_Software_Binar_attack_action_06fe9325"
    }
   ]
  },
  {
   "title": "Compromise_Host_Software_Binar_attack_action_74055752",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Host_Software_Binar_attack_action_74055752"
    }
   ]
  },
  {
   "title": "Compromise_Host_Software_Binar_attack_action_9215e2af",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Compromise_Host_Software_Binar_attack_action_9215e2af"
    }
   ]
  },
  {
   "title": "Credentials_in_Registry_attack_action_088f16ed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Credentials_in_Registry_attack_action_088f16ed"
    }
   ]
  },
  {
   "title": "Defense_Evasion_attack_action_62ff669d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Defense_Evasion_attack_action_62ff669d"
    }
   ]
  },
  {
   "title": "Exploit_Public_Facing_Applicat_attack_action_31a53687",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploit_Public_Facing_Applicat_attack_action_31a53687"
    }
   ]
  },
  {
   "title": "Impair_Defenses_attack_action_aed98895",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Impair_Defenses_attack_action_aed98895"
    }
   ]
  },
  {
   "title": "Internal_Proxy_attack_action_5e630b44",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Internal_Proxy_attack_action_5e630b44"
    }
   ]
  },
  {
   "title": "Internal_Proxy_attack_action_a5077335",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Internal_Proxy_attack_action_a5077335"
    }
   ]
  },
  {
   "title": "IvantiVulnerabilitiesOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_IvantiVulnerabilitiesOccurred"
    }
   ]
  },
  {
   "title": "LSASS_Memory_attack_action_896b159a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_LSASS_Memory_attack_action_896b159a"
    }
   ]
  },
  {
   "title": "NTDS_attack_action_55140b59",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_NTDS_attack_action_55140b59" }
   ]
  },
  {
   "title": "Persistence_attack_action_a3954799",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Persistence_attack_action_a3954799"
    }
   ]
  },
  {
   "title": "Reconnaissance_attack_action_9606315b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Reconnaissance_attack_action_9606315b"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_12d166be",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_12d166be"
    }
   ]
  },
  {
   "title": "System_Location_Discovery_attack_action_3b7d1c0f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_System_Location_Discovery_attack_action_3b7d1c0f"
    }
   ]
  },
  {
   "title": "Web_Portal_Capture_attack_action_33d36b98",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Web_Portal_Capture_attack_action_33d36b98"
    }
   ]
  }
 ]
}