{
 "title": "APT: ContiCISAAlert",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ContiCISAAlertOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_ContiCISAAlertOccurred" }
   ]
  },
  {
   "title": "Fake_Software_attack_action_57dca417",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Fake_Software_attack_action_57dca417"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_7a4205e1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_7a4205e1"
    }
   ]
  },
  {
   "title": "Social_Engineering_attack_action_0cf0c85b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Social_Engineering_attack_action_0cf0c85b"
    }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_2a8b2d9c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_2a8b2d9c"
    }
   ]
  },
  {
   "title": "Spearphishing_Link_attack_action_e51a777f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Link_attack_action_e51a777f"
    }
   ]
  },
  {
   "title": "attack_operator_7686e85f_53e7__attack_operator_7686e85f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_7686e85f_53e7__attack_operator_7686e85f"
    }
   ]
  },
  {
   "title": "attack_operator_ee2f9478_ca65__attack_operator_ee2f9478",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_ee2f9478_ca65__attack_operator_ee2f9478"
    }
   ]
  }
 ]
}