{
 "title": "APT: REvil",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Drive_by_Compromise_attack_action_94742c71",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Drive_by_Compromise_attack_action_94742c71"
    }
   ]
  },
  {
   "title": "Exploitation_for_Privilege_Esc_attack_action_817870ea",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploitation_for_Privilege_Esc_attack_action_817870ea"
    }
   ]
  },
  {
   "title": "Malicious_File_attack_action_0941f1e9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malicious_File_attack_action_0941f1e9"
    }
   ]
  },
  {
   "title": "REvilOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_REvilOccurred" }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_f0cc9e44",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_f0cc9e44"
    }
   ]
  },
  {
   "title": "attack_operator_f2b2f246_acf4__attack_operator_f2b2f246",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_f2b2f246_acf4__attack_operator_f2b2f246"
    }
   ]
  }
 ]
}