{
 "title": "APT: JPMorganBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "JPMorganBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_JPMorganBreachOccurred" }
   ]
  },
  {
   "title": "Phishing_attack_action_c4b5213a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Phishing_attack_action_c4b5213a"
    }
   ]
  },
  {
   "title": "attack_condition_05935c6a_636d_attack_condition_05935c6a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_05935c6a_636d_attack_condition_05935c6a"
    }
   ]
  }
 ]
}