{
 "title": "APT: EquifaxBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "EquifaxBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_EquifaxBreachOccurred" }
   ]
  },
  {
   "title": "Vulnerability_Scanning_attack_action_6f347c34",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Vulnerability_Scanning_attack_action_6f347c34"
    }
   ]
  },
  {
   "title": "attack_condition_6a38d6e6_107c_attack_condition_6a38d6e6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_6a38d6e6_107c_attack_condition_6a38d6e6"
    }
   ]
  }
 ]
}