{
 "title": "APT: Turla_CarbonEmulationPlan",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Spearphishing_Link_attack_action_0e541791",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Link_attack_action_0e541791"
    }
   ]
  },
  {
   "title": "Turla_CarbonEmulationPlanOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Turla_CarbonEmulationPlanOccurred"
    }
   ]
  },
  {
   "title": "attack_condition_5162318e_a7a9_attack_condition_5162318e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_5162318e_a7a9_attack_condition_5162318e"
    }
   ]
  }
 ]
}