{
 "title": "APT: MarriottBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Credentials_from_Password_Stor_attack_action_ccc7e534",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Credentials_from_Password_Stor_attack_action_ccc7e534"
    }
   ]
  },
  {
   "title": "MarriottBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_MarriottBreachOccurred" }
   ]
  },
  {
   "title": "Phishing_attack_action_2bf2f95c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Phishing_attack_action_2bf2f95c"
    }
   ]
  },
  {
   "title": "Remote_Access_Software_attack_action_9f740818",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Access_Software_attack_action_9f740818"
    }
   ]
  },
  {
   "title": "attack_condition_1c852859_2281_attack_condition_1c852859",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_1c852859_2281_attack_condition_1c852859"
    }
   ]
  },
  {
   "title": "attack_operator_1b533799_bd2f__attack_operator_1b533799",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_1b533799_bd2f__attack_operator_1b533799"
    }
   ]
  }
 ]
}