{
 "title": "APT: ContiRansomware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ContiRansomwareOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_ContiRansomwareOccurred" }
   ]
  },
  {
   "title": "Exfiltration_attack_action_726c3e3f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exfiltration_attack_action_726c3e3f"
    }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_8fbbfd31",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_8fbbfd31"
    }
   ]
  },
  {
   "title": "JavaScript_attack_action_7a811b31",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_JavaScript_attack_action_7a811b31"
    }
   ]
  },
  {
   "title": "Rundll32_attack_action_0cd8c60f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Rundll32_attack_action_0cd8c60f"
    }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_63b4d51e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_63b4d51e"
    }
   ]
  },
  {
   "title": "attack_condition_e9da9ad8_37a3_attack_condition_e9da9ad8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_e9da9ad8_37a3_attack_condition_e9da9ad8"
    }
   ]
  }
 ]
}