{
 "title": "APT: MITRENERVE",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Automated_Collection_attack_action_f0f30a1f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Automated_Collection_attack_action_f0f30a1f"
    }
   ]
  },
  {
   "title": "Boot_or_Logon_Initialization_S_attack_action_07a77101",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Boot_or_Logon_Initialization_S_attack_action_07a77101"
    }
   ]
  },
  {
   "title": "Browser_Information_Discovery_attack_action_4a9e529b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Browser_Information_Discovery_attack_action_4a9e529b"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_33bd811f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_33bd811f"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_5decc5bb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_5decc5bb"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_7774fba5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_7774fba5"
    }
   ]
  },
  {
   "title": "Command_and_Control_attack_action_fa467188",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Control_attack_action_fa467188"
    }
   ]
  },
  {
   "title": "Create_Virtual_Machines_attack_action_bfe2fdd1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Create_Virtual_Machines_attack_action_bfe2fdd1"
    }
   ]
  },
  {
   "title": "Data_Staged_attack_action_645367bc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Data_Staged_attack_action_645367bc"
    }
   ]
  },
  {
   "title": "Data_Staged_attack_action_a89d0430",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Data_Staged_attack_action_a89d0430"
    }
   ]
  },
  {
   "title": "Data_from_Local_System_attack_action_ca65fb33",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Data_from_Local_System_attack_action_ca65fb33"
    }
   ]
  },
  {
   "title": "Data_from_Local_System_attack_action_ddee5de8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Data_from_Local_System_attack_action_ddee5de8"
    }
   ]
  },
  {
   "title": "Defense_Evasion_attack_action_d651cb70",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Defense_Evasion_attack_action_d651cb70"
    }
   ]
  },
  {
   "title": "Discovery_attack_action_c5c2c45d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Discovery_attack_action_c5c2c45d"
    }
   ]
  },
  {
   "title": "Exfiltration_Over_Alternative__attack_action_9022b397",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exfiltration_Over_Alternative__attack_action_9022b397"
    }
   ]
  },
  {
   "title": "Exfiltration_Over_C2_Channel_attack_action_418c0c2f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exfiltration_Over_C2_Channel_attack_action_418c0c2f"
    }
   ]
  },
  {
   "title": "Exploit_Public_Facing_Applicat_attack_action_3211abb9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Exploit_Public_Facing_Applicat_attack_action_3211abb9"
    }
   ]
  },
  {
   "title": "File_and_Directory_Discovery_attack_action_3b80bacf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_File_and_Directory_Discovery_attack_action_3b80bacf"
    }
   ]
  },
  {
   "title": "File_and_Directory_Discovery_attack_action_853f83d4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_File_and_Directory_Discovery_attack_action_853f83d4"
    }
   ]
  },
  {
   "title": "Lateral_Movement_attack_action_18eb79ed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Lateral_Movement_attack_action_18eb79ed"
    }
   ]
  },
  {
   "title": "MITRENERVEOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_MITRENERVEOccurred" }
   ]
  },
  {
   "title": "Masquerade_File_Type_attack_action_a5f63fa5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Masquerade_File_Type_attack_action_a5f63fa5"
    }
   ]
  },
  {
   "title": "Network_Share_Discovery_attack_action_b3ffb250",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Network_Share_Discovery_attack_action_b3ffb250"
    }
   ]
  },
  {
   "title": "Python_attack_action_d6b7833a",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Python_attack_action_d6b7833a"
    }
   ]
  },
  {
   "title": "RC_Scripts_attack_action_38e9b5ff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_RC_Scripts_attack_action_38e9b5ff"
    }
   ]
  },
  {
   "title": "RDP_Hijacking_attack_action_04724f7f",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_RDP_Hijacking_attack_action_04724f7f"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_6c756d93",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_6c756d93"
    }
   ]
  },
  {
   "title": "Remote_Desktop_Protocol_attack_action_f5d7cebf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Desktop_Protocol_attack_action_f5d7cebf"
    }
   ]
  },
  {
   "title": "Remote_Services_attack_action_b5f01452",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Remote_Services_attack_action_b5f01452"
    }
   ]
  },
  {
   "title": "Run_Virtual_Instance_attack_action_3bb64c8b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Run_Virtual_Instance_attack_action_3bb64c8b"
    }
   ]
  },
  {
   "title": "Symmetric_Cryptography_attack_action_64f75253",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Symmetric_Cryptography_attack_action_64f75253"
    }
   ]
  },
  {
   "title": "Valid_Accounts_attack_action_926e83ad",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Valid_Accounts_attack_action_926e83ad"
    }
   ]
  },
  {
   "title": "Web_Shell_attack_action_77d4f01d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Web_Shell_attack_action_77d4f01d"
    }
   ]
  },
  {
   "title": "attack_operator_818bc7c8_2eb5__attack_operator_818bc7c8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_818bc7c8_2eb5__attack_operator_818bc7c8"
    }
   ]
  }
 ]
}