{
 "title": "APT: CobaltKittyCampaign",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CobaltKittyCampaignOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_CobaltKittyCampaignOccurred" }
   ]
  },
  {
   "title": "PowerShell_attack_action_d3d7d621",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_PowerShell_attack_action_d3d7d621"
    }
   ]
  },
  {
   "title": "Scheduled_Task_attack_action_217d8b41",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Scheduled_Task_attack_action_217d8b41"
    }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_508bc600",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_508bc600"
    }
   ]
  },
  {
   "title": "Spearphishing_Link_attack_action_7e43c3eb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Link_attack_action_7e43c3eb"
    }
   ]
  },
  {
   "title": "attack_operator_5c3ac180_7cb9__attack_operator_5c3ac180",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_5c3ac180_7cb9__attack_operator_5c3ac180"
    }
   ]
  }
 ]
}