{
 "title": "APT: HancitorDLL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HancitorDLLOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_HancitorDLLOccurred" }
   ]
  },
  {
   "title": "Ingress_Tool_Transfer_attack_action_5d55cc3d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Ingress_Tool_Transfer_attack_action_5d55cc3d"
    }
   ]
  },
  {
   "title": "Malicious_File_attack_action_1d851bc1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malicious_File_attack_action_1d851bc1"
    }
   ]
  },
  {
   "title": "Process_Injection_attack_action_264c553e",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Process_Injection_attack_action_264c553e"
    }
   ]
  },
  {
   "title": "Rundll32_attack_action_8ec450fa",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Rundll32_attack_action_8ec450fa"
    }
   ]
  },
  {
   "title": "Spearphishing_Link_attack_action_0fc122a5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Link_attack_action_0fc122a5"
    }
   ]
  },
  {
   "title": "Visual_Basic_attack_action_7f226db5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Visual_Basic_attack_action_7f226db5"
    }
   ]
  },
  {
   "title": "attack_condition_a2793461_43b8_attack_condition_a2793461",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_a2793461_43b8_attack_condition_a2793461"
    }
   ]
  }
 ]
}