{
 "title": "APT: TeslaKubernetesBreach",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Non_Standard_Port_attack_action_d1ea11b4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Non_Standard_Port_attack_action_d1ea11b4"
    }
   ]
  },
  {
   "title": "Proxy_attack_action_837bede5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Proxy_attack_action_837bede5"
    }
   ]
  },
  {
   "title": "Server_attack_action_ec83e8c9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Server_attack_action_ec83e8c9"
    }
   ]
  },
  {
   "title": "TeslaKubernetesBreachOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_TeslaKubernetesBreachOccurred"
    }
   ]
  },
  {
   "title": "attack_condition_394e0f5c_534b_attack_condition_394e0f5c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_394e0f5c_534b_attack_condition_394e0f5c"
    }
   ]
  },
  {
   "title": "attack_operator_2523aded_6d9a__attack_operator_2523aded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_2523aded_6d9a__attack_operator_2523aded"
    }
   ]
  }
 ]
}