{
 "title": "APT: SolarWinds",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Code_Signing_attack_action_fce268a4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Code_Signing_attack_action_fce268a4"
    }
   ]
  },
  {
   "title": "Malware_attack_action_384373d8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Malware_attack_action_384373d8"
    }
   ]
  },
  {
   "title": "SolarWindsOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_SolarWindsOccurred" }
   ]
  },
  {
   "title": "attack_operator_b0aa9f11_7722__attack_operator_b0aa9f11",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_b0aa9f11_7722__attack_operator_b0aa9f11"
    }
   ]
  }
 ]
}