{
 "title": "APT: BlackBastaRansomware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Account_Manipulation_attack_action_599cf0b7",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Account_Manipulation_attack_action_599cf0b7"
    }
   ]
  },
  {
   "title": "BlackBastaRansomwareOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_BlackBastaRansomwareOccurred"
    }
   ]
  },
  {
   "title": "Command_and_Scripting_Interpre_attack_action_b681891b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Scripting_Interpre_attack_action_b681891b"
    }
   ]
  },
  {
   "title": "Command_and_Scripting_Interpre_attack_action_ec4f8e09",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Command_and_Scripting_Interpre_attack_action_ec4f8e09"
    }
   ]
  },
  {
   "title": "Create_Account_attack_action_d88229be",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Create_Account_attack_action_d88229be"
    }
   ]
  },
  {
   "title": "Create_or_Modify_System_Proces_attack_action_a33a2a3b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Create_or_Modify_System_Proces_attack_action_a33a2a3b"
    }
   ]
  },
  {
   "title": "DeobfuscateDecode_Files_or_Inf_attack_action_b2345e48",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_DeobfuscateDecode_Files_or_Inf_attack_action_b2345e48"
    }
   ]
  },
  {
   "title": "Domain_Policy_Modification_Gro_attack_action_1ab99f8c",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Domain_Policy_Modification_Gro_attack_action_1ab99f8c"
    }
   ]
  },
  {
   "title": "Hijack_Execution_Flow_DLL_Sear_attack_action_c94bdb43",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Hijack_Execution_Flow_DLL_Sear_attack_action_c94bdb43"
    }
   ]
  },
  {
   "title": "Phishing_Spearphishing_Attachm_attack_action_a3679838",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Phishing_Spearphishing_Attachm_attack_action_a3679838"
    }
   ]
  },
  {
   "title": "System_Binary_Proxy_Execution__attack_action_9f5746cd",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_System_Binary_Proxy_Execution__attack_action_9f5746cd"
    }
   ]
  },
  {
   "title": "User_Execution_Malicious_File_attack_action_e5715d9b",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_User_Execution_Malicious_File_attack_action_e5715d9b"
    }
   ]
  },
  {
   "title": "attack_operator_14c72b05_5f68__attack_operator_14c72b05",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_operator_14c72b05_5f68__attack_operator_14c72b05"
    }
   ]
  }
 ]
}