{
 "title": "APT: OceanLotus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "OceanLotusOccurred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "bn_OceanLotusOccurred" }
   ]
  },
  {
   "title": "Spearphishing_Attachment_attack_action_8196f7e1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_Spearphishing_Attachment_attack_action_8196f7e1"
    }
   ]
  },
  {
   "title": "attack_condition_4d72adde_a31f_attack_condition_4d72adde",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_4d72adde_a31f_attack_condition_4d72adde"
    }
   ]
  },
  {
   "title": "attack_condition_53ab2436_71dc_attack_condition_53ab2436",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bn_attack_condition_53ab2436_71dc_attack_condition_53ab2436"
    }
   ]
  }
 ]
}